# -*- coding: utf-8 -*-
"""NER_Mountains_inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDgu1qz-KixngOERYmMUYTJTH6mEGhGy
"""

def highlight_entities(sentence, entities):
    offset = 0
    for entity in entities:
        start = entity['start'] + offset
        end = entity['end'] + offset
        tag = entity['entity']
        sentence = sentence[:start] + '{('+ tag +')' + sentence[start:end] + '}' + sentence[end:]
        offset += 5
    return sentence

from transformers import pipeline
pipe = pipeline("token-classification", model="Worpl/BERT-finetuned-ner-mountains")

while True:
    user_input = input("Input sentence to predict named mountains, or \"exit\" to exit: ")
    if user_input == "exit":
        break
    entities = pipe(user_input)
    print(highlight_entities(user_input, entities))

print("Done.")

